# These are supported funding model platforms

github: [ermradulsharma]
patreon: ermradulsharma
open_collective: ermradulsharma
ko_fi: ermradulsharma
buy_me_a_coffee: ermradulsharma
tidelift: npm/your-package-name
liberapay: ermradulsharma
issuehunt: ermradulsharma
# custom: ['https://paypal.me/ermradulsharma', 'https://www.pahadigo.co.in/sponsor']