const customJestConfig = {
    testEnvironment: 'node',
    setupFilesAfterEnv: ['./tests/setup.js'],
    testTimeout: 120000,
    moduleNameMapper: {
        '\\.jsx$': '<rootDir>/tests/__mocks__/jsxMock.js',
        '^@/models$': '<rootDir>/src/core/Models/index.js',
        '^@/models/(.*)$': '<rootDir>/src/core/Models/$1',
        '^@/services$': '<rootDir>/src/core/Services/index.js',
        '^@/services/(.*)$': '<rootDir>/src/core/Services/$1',
        '^@/constants$': '<rootDir>/src/core/Constants/index.js',
        '^@/constants/(.*)$': '<rootDir>/src/core/Constants/$1',
        '^@/helpers$': '<rootDir>/src/core/Helpers/index.js',
        '^@/helpers/(.*)$': '<rootDir>/src/core/Helpers/$1',
        '^@/lib$': '<rootDir>/src/core/Lib/index.js',
        '^@/lib/(.*)$': '<rootDir>/src/core/Lib/$1',
        '^@/controllers/(.*)$': '<rootDir>/src/core/Http/Controllers/$1',
        '^@/core/Controllers/(.*)$': '<rootDir>/src/core/Http/Controllers/$1',
        '^@/middleware/(.*)$': '<rootDir>/src/core/Http/Middleware/$1',
        '^@/core/Middleware/(.*)$': '<rootDir>/src/core/Http/Middleware/$1',
        '^@/routes/(.*)$': '<rootDir>/src/core/Routes/$1',
        '^@/core/Routes/(.*)$': '<rootDir>/src/core/Routes/$1',
        '^@/config/(.*)$': '<rootDir>/src/core/Config/$1',
        '^@/core/Config/(.*)$': '<rootDir>/src/core/Config/$1',
        '^@/seeders/(.*)$': '<rootDir>/src/core/Database/Seeders/$1',
        '^@/core/Seeders/(.*)$': '<rootDir>/src/core/Database/Seeders/$1',
        '^@/core/Constants/(.*)$': '<rootDir>/src/core/Constants/$1',
        '^@/core/Helpers/(.*)$': '<rootDir>/src/core/Helpers/$1',
        '^@/core/Models/(.*)$': '<rootDir>/src/core/Models/$1',
        '^@/core/Services/(.*)$': '<rootDir>/src/core/Services/$1',
        '^@/core/Lib/(.*)$': '<rootDir>/src/core/Lib/$1',
        '^@/database/Seeders/(.*)$': '<rootDir>/src/core/Database/Seeders/$1',
        '^@/events/(.*)$': '<rootDir>/src/core/Events/$1',
        '^@/(.*)$': '<rootDir>/src/$1',
    },
};

module.exports = customJestConfig;
